import "globals.css"
import { Theme } from "@radix-ui/react-theme";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Theme>
      <body>{children}</body>
      </Theme>
    </html>
  );
}